#set document(title: "Tetris MCTS Architecture and Runtime")
#set page(width: 8.5in, height: 11in, margin: (x: 1in, y: 0.95in))
#set text(font: "Libertinus Serif", size: 11pt)
#set par(justify: true, leading: 0.65em)
#show figure.caption: set text(size: 10pt)

= Network Architecture

Figure @fig:network-architecture shows the current network used by the system. The board occupancy tensor flows through the cached convolutional backbone, engineered board statistics are injected at `board_proj`, and the piece/game context modulates the cached board embedding before the policy and value heads.

#figure(
  image("../plots/network_architecture.pdf", width: 100%),
  caption: [
    Current architecture. Inputs are split into a `1 x 20 x 10` board tensor, `19` custom board-stat features, and `61` piece/game features. The custom board stats are column heights, max height, bottom-row fill counts, total blocks, bumpiness, holes, and overhang fields. The piece/game features are current piece, hold piece, hold availability, next queue, placement count, combo, back-to-back state, and hidden-piece distribution. The board path produces a cached `board_h` embedding, the aux path produces a separate embedding, and the concatenated representation feeds the `735`-logit policy head and scalar value head. The runtime split model is `conv.onnx + fc.bin + heads.onnx`, with `board_h` cached by board state.
  ],
) <fig:network-architecture>

= Runtime and Average Attack

This figure compares average attack against whole-game runtime for several configurations.

#figure(
  image("../plots/avg_attack_vs_runtime.pdf", width: 100%),
  caption: [
    Average attack versus whole-game runtime. Lower runtime is better, so the x-axis is reversed. Marker shape encodes simulation budget.
  ],
) <fig:runtime-attack>

Figure @fig:runtime-attack is generated by `paper/build.sh`, which regenerates the architecture diagram and runtime plot before compiling this Typst document into `paper/paper.pdf`.
